version: 2.1
orbs:
  cypress: cypress-io/cypress@3
workflows:
  test:
    jobs:
      - cypress/run:
          install-browsers: true
          start-command: 'npm run start'
          cypress-command: 'cypress run --spec cypress/e2e/ContactDirect/Drugs/Labels.cy.js --browser chrome'