version: '2.1'

jobs:
  test:
    docker:
      - image: cypress/included:13.11.0
    steps:
      - checkout

      - run:
          name: Run Cypress Tests in Chrome
          command: npx cypress run --browser chrome --headed --spec "cypress/e2e/Home/FDA_Registarion/FoodFacility/FFViewCeritificates.cy.js"

      - run:
          name: Zip Test Report
          command: node ./scripts/zipScript.js

      - store_artifacts:
          path: cypress/reports/mochawesome-report/report.zip
          destination: TestReport

workflows:
  run-tests:
    jobs:
      - test
