version: '2.1'

orbs:
  cypress: cypress-io/cypress@3.1.4

jobs:
  test:
    docker:
      - image: cypress/browsers:node-20.18.0-chrome-130.0.6723.69-1-ff-131.0.3-edge-130.0.2849.52-1
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: npm ci

      - run:
          name: Run Cypress in Firefox
          command: npx cypress run --browser firefox --headed --spec "cypress/e2e/Home/FDA_Registarion/FoodFacility/FFViewCeritificates.cy.js"

      - run:
          name: Zip test report
          command: node ./scripts/zipScript.js

      - store_artifacts:
          path: cypress/reports/mochawesome-report/report.zip
          destination: TestReport

workflows:
  run-tests:
    jobs:
      - test
