version: '2.1'

orbs:
  cypress: cypress-io/cypress@3.1.4
  browser-tools: circleci/browser-tools@1.4.4

workflows:
  run-tests:
    jobs:
      - cypress/run:
          name: Cypress tests in Firefox
          browser: firefox
          headed: true
          start-command: 'npm start'
          wait-on: 'http://localhost:3000'
          spec: cypress/e2e/Home/FDA_Registarion/FoodFacility/FFViewCeritificates.cy.js
          post-steps:
            - run:
                name: Run zip script
                command: node ./scripts/zipScript.js
            - store_artifacts:
                path: cypress/reports/mochawesome-report/report.zip
                destination: TestReport
