version: '2.1'
orbs:
  cypress: cypress-io/cypress@3.1.4
workflows:
  use-my-orb:
    jobs:
      - cypress/run:
          cypress-command: npx cypress run --browser chrome --headed --spec cypress/e2e/ContactDirect/Drugs/Labels.cy.js 
                           node ./scripts/zipScript.js
          install-browsers: true
          post-steps:
              - run: ls
              - store_artifacts:
                  path: cypress/reports/mochawesome-report/report.zip
                  destination: TestReport
