version: '2.1'
orbs:
  cypress: cypress-io/cypress@3.1.4
workflows:
  use-my-orb:
    browser-tools: circleci/browser-tools@1.5.3 # or the latest version
    jobs:
      - browser-tools/install-browser-tools:
          version: "latest"
          install-firefox: true
          install-geckodriver: true
      - cypress/run:
          cypress-command: npx cypress run --browser chrome --headed --spec cypress\e2e\Home\FDA_Registarion\FoodFacility\FFViewCeritificates.cy.js 
                           node ./scripts/zipScript.js
          post-steps:
              - run: ls
              - store_artifacts:
                  path: cypress/reports/mochawesome-report/report.zip
                  destination: TestReport
